# After changing this file, check it on:
#   http://lint.travis-ci.org/

language: c++

# Run jobs on container-based infrastructure, can be overridden per job
sudo: false

matrix:
  - python: 3.5

before_install:
  - uname -a
  - free -m
  - df -h
  - ulimit -a

install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -n libnugrid python=3.5 pytest pytest-cov pyyaml numpy cmake scipy numexpr mkl-include gcc-5-mp -c intel
  - source activate libnugrid
  - pip install codecov
  - conda list

before_script:
  - python -V

script:
  - cd libnugrid
  - mkdir build
  - cd build
  - cmake ..
  - make
  - make install
  - cd ../../tests
  - make
  - ./main 0.1 

notifications:
  email: false

after_success:
  - codecov
